// The root project name
rootProject.name='openflexo-dev'

// The list of projects you will work on
// For each projects, you must have a 'checkouted' version of the corresponding repository
// The includes below suppose that the local copy of the needed repositories are in the parent directory of the current directory
includeBuild '../openflexo-buildplugin'
includeBuild '../connie'
includeBuild '../diana'
includeBuild '../gina'
includeBuild '../pamela'
includeBuild '../pamela-editor'
includeBuild '../openflexo-utils'
includeBuild '../openflexo-core'
includeBuild '../openflexo-ui'
includeBuild '../modelers'
includeBuild '../openflexo-integration-tests'
includeBuild '../openflexo-packaging'
//includeBuild '../pimca'
//includeBuild '../cta'
//includeBuild '../formod'

// Technology adapters
includeBuild '../openflexo-technology-adapters'
includeBuild '../openflexo-diagram'
includeBuild '../openflexo-docx'
includeBuild '../openflexo-emf'
includeBuild '../openflexo-gina'
//includeBuild '../openflexo-http'
includeBuild '../openflexo-rest'
includeBuild '../openflexo-java'
includeBuild '../openflexo-jdbc'
includeBuild '../openflexo-kafka'
includeBuild '../openflexo-owl'
includeBuild '../openflexo-opc-ua'
includeBuild '../openflexo-capella'
//includeBuild '../openflexo-obp2'
includeBuild '../openflexo-odt'
includeBuild '../openflexo-oslc'
includeBuild '../openflexo-pdf'
includeBuild '../openflexo-pptx'
includeBuild '../openflexo-rhapsody'
includeBuild '../openflexo-xlsx'
includeBuild '../openflexo-xml'
includeBuild '../openflexo-json'
//includeBuild '../openflexo-markdown'
includeBuild '../openflexo-mcp'
includeBuild '../openflexo-csv'

// Server
includeBuild '../openflexo-server'

// Application modules
includeBuild '../openflexo-modules'
includeBuild '../openflexo-modeller'
includeBuild '../free-modelling-editor'
includeBuild '../enterprise-architecture-editor'

